### ISSUE TITLE
[BUG] players be kicked from the server sometimes

### ISSUE THREAD

**Issue by Mooshed88** [Ghost-chu/QuickShop-Hikari#1030]
### Description

When players click the shop, or use any commands, They may be kicked off the server. This is the error:
[15:32:27] [Server thread/INFO]: Herobrine issued server command: /qs price 15
[15:32:34] [Server thread/INFO]: Herobrine issued server command: /qs silentremove 2772cc8e-64fd-455d-9d5f-e279060de071
[15:32:45] [Netty Server IO #0/ERROR]: Packet encoding of packet ID 10 threw (skippable? false)
io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
	at net.minecraft.network.FriendlyByteBuf.writeNbt(FriendlyByteBuf.java:450) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.write(ClientboundBlockEntityDataPacket.java:43) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.18.2.jar:git-Paper-388]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at me.arasple.mc.trchat.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:22) ~[TrChat-2.0.0-PRE-40.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:462) ~[?:?]
	at net.minecraft.network.Connection.lambda$writePacket$11(Connection.java:436) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:678) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$KeyIterator.next(Object2ObjectOpenHashMap.java:1083) ~[fastutil-8.5.6.jar:?]
	at net.minecraft.nbt.CompoundTag.write(CompoundTag.java:136) ~[?:?]
	at net.minecraft.nbt.NbtIo.writeUnnamedTag(NbtIo.java:280) ~[?:?]
	at net.minecraft.nbt.NbtIo.write(NbtIo.java:248) ~[?:?]
	at net.minecraft.network.FriendlyByteBuf.writeNbt(FriendlyByteBuf.java:448) ~[?:?]
	... 32 more
[15:32:45] [Server thread/INFO]: Herobrine lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
[15:32:45] [Server thread/INFO]: Herobrine left the game

### Steps to reproduce

1. Install the plugin.
2. Players create a chest shop and use it.
3. There is a probability that the player will be kicked out.

### Expected Behaviour

Players won't be kicked out and there's no error in the console.

### Screenshots

![Screeshot 2023-08-14 212208](https://github.com/Ghost-chu/QuickShop-Hikari/assets/110685419/08ecc299-435c-4218-9022-019fce78b919)

### `/qs paste` URL

When I run /qs paste, it says "paste-warning-plugin-find". Instead this is a log (errors are at about line 27937, 28073 and 30006)
[latest.log](https://github.com/Ghost-chu/QuickShop-Hikari/files/12334983/latest.log)

**Comment by YuanYuanOwO** [comment]
`/qs paste --force`

**Comment by Ghost-chu** [comment]
It seems caused by TrChat plugin, please contact TrChat plugin developer.

**Comment by Ghost-chu** [comment]
Feel free to comment under this issue to reopen it when TrChat developer think its a quickshop error
