### ISSUE TITLE
[BUG] DiscordSRV Addon 5.0.0.1 runtime error when sending embed messages

### ISSUE THREAD

**Issue by Subdevell** [Ghost-chu/QuickShop-Hikari#1059]
### Description

The DiscordSRV addon doesn't send discord messages when buying items anymore. Neither the DM message or the mod channel message.

The following exception is sent in the console : 
`[19:34:34 WARN]: [QuickShop-Hikari] Plugin QuickShop-Hikari v5.0.0.1 generated an exception while executing task 1987463
java.lang.IllegalArgumentException: argument type mismatch
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.ghostchu.quickshop.addon.discordsrv.message.MessageManager.getEmbedMessage(MessageManager.java:68) ~[Addon-DiscordSRV-5.0.0.1.jar:?]
        at com.ghostchu.quickshop.addon.discordsrv.message.MessageFactory.shopPermissionChanged(MessageFactory.java:200) ~[Addon-DiscordSRV-5.0.0.1.jar:?]
        at com.ghostchu.quickshop.addon.discordsrv.listener.QuickShopEventListener.lambda$notifyShopPermissionChanged$11(QuickShopEventListener.java:189) ~[Addon-DiscordSRV-5.0.0.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-108]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-108]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

### Steps to reproduce

1. Configure DiscordSRV to send messages when buying items.
2. Buy an item from a shop.
3. Check the console for the exception.

### Expected Behaviour

The message configured in the lang file should be sent in DM and in the mod configured channel.

### Screenshots

No screenshots

### `/quickshop  paste` URL

https://paste.helpch.at/owegixeyep.swift

### Additional Context

After some digging, it seems to be a reflection issue in the MessageManager class. 

The method boughtFromShop in MessageRepository expect a UUID as first argument. [Code Here](https://github.com/Ghost-chu/QuickShop-Hikari/blob/5c716260b38f9df2d29c7eb107e06ba7d305b37a/addon/discordsrv/src/main/java/com/ghostchu/quickshop/addon/discordsrv/message/MessageRepository.java#L117C54-L117C54)

The method getEmbedMessage gives a QUser in the method invoke. [Code Here](https://github.com/Ghost-chu/QuickShop-Hikari/blob/5c716260b38f9df2d29c7eb107e06ba7d305b37a/addon/discordsrv/src/main/java/com/ghostchu/quickshop/addon/discordsrv/message/MessageManager.java#L68C80-L68C80)

**Comment by YuanYuanOwO** [comment]
Seems the paste URL is wrong
