### ISSUE TITLE
[BUG]Latest TheNewEconomy doesn't work

### ISSUE THREAD

**Issue by YuanYuanOwO** [Ghost-chu/QuickShop-Hikari#1061]
```yaml
[16:05:40 WARN]: [QuickShop-Hikari] Task #38 for QuickShop-Hikari v5.0.0.2 generated an exception
java.lang.NoClassDefFoundError: net/tnemc/core/TNE
        at com.ghostchu.quickshop.economy.Economy_TNE.setupEconomy(Economy_TNE.java:46) ~[QuickShop-Hikari-5.0.0.2.jar:?]
        at com.ghostchu.quickshop.economy.Economy_TNE.<init>(Economy_TNE.java:38) ~[QuickShop-Hikari-5.0.0.2.jar:?]
        at com.ghostchu.quickshop.QuickShop$EconomyLoader.loadTNE(QuickShop.java:1157) ~[QuickShop-Hikari-5.0.0.2.jar:?]        at com.ghostchu.quickshop.QuickShop$EconomyLoader.setupEconomy(QuickShop.java:1097) ~[QuickShop-Hikari-5.0.0.2.jar:?]
        at com.ghostchu.quickshop.QuickShop$EconomyLoader.load(QuickShop.java:1079) ~[QuickShop-Hikari-5.0.0.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2049]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2049]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1128) ~[purpur-1.20.1.jar:git-Purpur-2049]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2049]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.tnemc.core.TNE
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 10 more
```
TNE Version: 0.1.2.0 - Build: Pre-28

**Comment by Ghost-chu** [comment]
No plan to update TNE at this moment, the API stuff not up-to-date
