### ISSUE TITLE
[BUG] Mohist startup issue (libby didn't work on Mohist or similar hybird server)

### ISSUE THREAD

**Issue by svenlameir** [Ghost-chu/QuickShop-Hikari#1476]
### Description

Startup with the latest mohist build is unable to start quickshop

### Steps to reproduce

install latest mohist
install vault
install quickshop

### Expected Behaviour

start

### Screenshots

```
Error occurred while enabling QuickShop-Hikari v6.0.0.10 (Is it up to date?)
java.lang.IllegalStateException: Plugin is disabled due an loading error
	at com.ghostchu.quickshop.QuickShopBukkit.onEnable(QuickShopBukkit.java:101) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.2.21-universal.jar%23235!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.2.21-universal.jar%23235!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.21-universal.jar%23235!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549) ~[forge-1.20.1-47.2.21-universal.jar%23235!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462) ~[forge-1.20.1-47.2.21-universal.jar%23235!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23230!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23230!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:224) ~[server-1.20.1-20230612.114412-srg.jar%23230!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:848) ~[server-1.20.1-20230612.114412-srg.jar%23230!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23230!/:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.ghostchu.quickshop.shade.com.alessiodp.libby.transitive.TransitiveDependencyHelper.<init>(TransitiveDependencyHelper.java:101) ~[?:?]
	at com.ghostchu.quickshop.shade.com.alessiodp.libby.LibraryManager.resolveTransitiveLibraries(LibraryManager.java:651) ~[?:?]
	at com.ghostchu.quickshop.shade.com.alessiodp.libby.LibraryManager.loadLibrary(LibraryManager.java:674) ~[?:?]
	at com.ghostchu.quickshop.QuickShopBukkit.loadLibraries(QuickShopBukkit.java:213) ~[?:?]
	at com.ghostchu.quickshop.QuickShopBukkit.resolveLibraries(QuickShopBukkit.java:164) ~[?:?]
	at com.ghostchu.quickshop.QuickShopBukkit.loadLibraries(QuickShopBukkit.java:119) ~[?:?]
	at com.ghostchu.quickshop.QuickShopBukkit.onLoad(QuickShopBukkit.java:69) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:441) ~[forge-1.20.1-47.2.21-universal.jar%23235!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:216) ~[server-1.20.1-20230612.114412-srg.jar%23230!/:?]
	... 3 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.ghostchu.quickshop.shade.com.alessiodp.libby.transitive.TransitiveDependencyHelper.<init>(TransitiveDependencyHelper.java:88) ~[?:?]
	at com.ghostchu.quickshop.shade.com.alessiodp.libby.LibraryManager.resolveTransitiveLibraries(LibraryManager.java:651) ~[?:?]
	at com.ghostchu.quickshop.shade.com.alessiodp.libby.LibraryManager.loadLibrary(LibraryManager.java:674) ~[?:?]
	at com.ghostchu.quickshop.QuickShopBukkit.loadLibraries(QuickShopBukkit.java:213) ~[?:?]
	at com.ghostchu.quickshop.QuickShopBukkit.resolveLibraries(QuickShopBukkit.java:164) ~[?:?]
	at com.ghostchu.quickshop.QuickShopBukkit.loadLibraries(QuickShopBukkit.java:119) ~[?:?]
	at com.ghostchu.quickshop.QuickShopBukkit.onLoad(QuickShopBukkit.java:69) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:441) ~[forge-1.20.1-47.2.21-universal.jar%23235!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:216) ~[server-1.20.1-20230612.114412-srg.jar%23230!/:?]
	... 3 more
Caused by: java.lang.IllegalAccessError: class org.eclipse.aether.supplier.RepositorySystemSupplier tried to access method 'void org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.<init>(org.eclipse.aether.internal.impl.TrackingFileManager, org.eclipse.aether.impl.UpdatePolicyAnalyzer)' (org.eclipse.aether.supplier.RepositorySystemSupplier is in unnamed module of loader com.ghostchu.quickshop.shade.com.alessiodp.libby.classloader.IsolatedClassLoader @6e535661; org.eclipse.aether.internal.impl.DefaultUpdateCheckManager is in module org.apache.maven.resolver.impl@1.7.3 of loader 'MC-BOOTSTRAP' @34bde49d)
	at org.eclipse.aether.supplier.RepositorySystemSupplier.getUpdateCheckManager(RepositorySystemSupplier.java:173) ~[?:?]
	at org.eclipse.aether.supplier.RepositorySystemSupplier.get(RepositorySystemSupplier.java:525) ~[?:?]
	at com.ghostchu.quickshop.shade.com.alessiodp.libby.transitive.TransitiveDependencyCollector.newRepositorySystem(TransitiveDependencyCollector.java:150) ~[?:?]
	at com.ghostchu.quickshop.shade.com.alessiodp.libby.transitive.TransitiveDependencyCollector.<init>(TransitiveDependencyCollector.java:44) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.ghostchu.quickshop.shade.com.alessiodp.libby.transitive.TransitiveDependencyHelper.<init>(TransitiveDependencyHelper.java:88) ~[?:?]
	at com.ghostchu.quickshop.shade.com.alessiodp.libby.LibraryManager.resolveTransitiveLibraries(LibraryManager.java:651) ~[?:?]
	at com.ghostchu.quickshop.shade.com.alessiodp.libby.LibraryManager.loadLibrary(LibraryManager.java:674) ~[?:?]
	at com.ghostchu.quickshop.QuickShopBukkit.loadLibraries(QuickShopBukkit.java:213) ~[?:?]
	at com.ghostchu.quickshop.QuickShopBukkit.resolveLibraries(QuickShopBukkit.java:164) ~[?:?]
	at com.ghostchu.quickshop.QuickShopBukkit.loadLibraries(QuickShopBukkit.java:119) ~[?:?]
	at com.ghostchu.quickshop.QuickShopBukkit.onLoad(QuickShopBukkit.java:69) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:441) ~[forge-1.20.1-47.2.21-universal.jar%23235!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:216) ~[server-1.20.1-20230612.114412-srg.jar%23230!/:?]
	... 3 more
[21:50:30 INFO]: [QuickShop-Hikari] Disabling QuickShop-Hikari v6.0.0.10
[21:50:30 ERROR]: Error occurred while disabling QuickShop-Hikari v6.0.0.10 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.slf4j.Logger.info(String)" because "this.logger" is null
	at com.ghostchu.quickshop.QuickShopBukkit.onDisable(QuickShopBukkit.java:86) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:349) ~[forge-1.20.1-47.2.21-universal.jar%23235!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:365) ~[forge-1.20.1-47.2.21-universal.jar%23235!/:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:507) ~[forge-1.20.1-47.2.21-universal.jar%23235!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) ~[forge-1.20.1-47.2.21-universal.jar%23235!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.21-universal.jar%23235!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549) ~[forge-1.20.1-47.2.21-universal.jar%23235!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462) ~[forge-1.20.1-47.2.21-universal.jar%23235!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23230!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23230!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:224) ~[server-1.20.1-20230612.114412-srg.jar%23230!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:848) ~[server-1.20.1-20230612.114412-srg.jar%23230!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23230!/:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

### `/quickshop paste` URL

not posible

**Comment by Ghost-chu** [comment]
We confirm that this is a known issue. Unfortunately there is no way to fix it at this time other than upgrading to 1.20.2+ (newer versions of NeoForge no longer use the modular system).  
We will continue to explore solutions in the future, but we can't guarantee it will be fixed.

**Comment by Cats1337** [comment]
https://essentialsx.net/do-not-use-mohist.html
Use Archlight, Mohist is not something you ant to use...

**Comment by creatorfromhell** [comment]
Going to close this as it seems out of scope for the moment, would accept a PR on it, but generally most of these softwares are not stable.
