### ISSUE TITLE
[BUG] Velocity Compatibility Modules have error when creating price

### ISSUE THREAD

**Issue by mangocraft** [Ghost-chu/QuickShop-Hikari#1575]
### Description

This is a subserver under Velocity, using purpur1.20.4, Velocity compatible module has been installed and written the startup flag -Dcom.ghostchu.quickshop.util.Util.forceBungeeCord=true in start.bat
But when entering the price, the following error appears:
[17:19:42 WARN]: [QuickShop-Hikari] Plugin QuickShop-Hikari v6.2.0.0 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:472) ~[guava-32.1.2-jre.jar:?]
        at com.ghostchu.quickshop.listener.BungeeListener.onPluginMessageReceived(BungeeListener.java:74) ~[QuickShop-Hikari-6.2.0.0.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleCustomPayload(ServerCommonPacketListenerImpl.java:183) ~[purpur-1.20.4.jar:git-Purpur-2165]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:46) ~[purpur-1.20.4.jar:git-Purpur-2165]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.a(ServerboundCustomPayloadPacket.java:12) ~[purpur-1.20.4.jar:git-Purpur-2165]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2165]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1498) ~[purpur-1.20.4.jar:git-Purpur-2165]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2165]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1475) ~[purpur-1.20.4.jar:git-Purpur-2165]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1398) ~[purpur-1.20.4.jar:git-Purpur-2165]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1376) ~[purpur-1.20.4.jar:git-Purpur-2165]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1265) ~[purpur-1.20.4.jar:git-Purpur-2165]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2165]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.io.EOFException
        at java.io.DataInputStream.readFully(DataInputStream.java:210) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:594) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:550) ~[?:?]
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:470) ~[guava-32.1.2-jre.jar:?]
        
 

### Steps to reproduce

1. Use the item to long press the box
2. Enter the price
3. No response

### Expected Behaviour

Normally create a quickshop

### Screenshots

![image](https://github.com/Ghost-chu/QuickShop-Hikari/assets/24970475/bc62f56d-9717-4802-8124-b7fadedda6e7)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FCucL2Rj0YM

**Comment by creatorfromhell** [comment]
> ### Description
> This is a subserver under Velocity, using purpur1.20.4, Velocity compatible module has been installed and written the startup flag -Dcom.ghostchu.quickshop.util.Util.forceBungeeCord=true in start.bat But when entering the price, the following error appears: [17:19:42 WARN]: [QuickShop-Hikari] Plugin QuickShop-Hikari v6.2.0.0 generated an exception whilst handling plugin message java.lang.IllegalStateException: java.io.EOFException at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:472) ~[guava-32.1.2-jre.jar:?] at com.ghostchu.quickshop.listener.BungeeListener.onPluginMessageReceived(BungeeListener.java:74) ~[QuickShop-Hikari-6.2.0.0.jar:?] at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?] at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleCustomPayload(ServerCommonPacketListenerImpl.java:183) ~[purpur-1.20.4.jar:git-Purpur-2165] at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:46) ~[purpur-1.20.4.jar:git-Purpur-2165] at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.a(ServerboundCustomPayloadPacket.java:12) ~[purpur-1.20.4.jar:git-Purpur-2165] at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2165] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1498) ~[purpur-1.20.4.jar:git-Purpur-2165] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2165] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1475) ~[purpur-1.20.4.jar:git-Purpur-2165] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1398) ~[purpur-1.20.4.jar:git-Purpur-2165] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?] at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1376) ~[purpur-1.20.4.jar:git-Purpur-2165] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1265) ~[purpur-1.20.4.jar:git-Purpur-2165] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2165] at java.lang.Thread.run(Thread.java:1583) ~[?:?] Caused by: java.io.EOFException at java.io.DataInputStream.readFully(DataInputStream.java:210) ~[?:?] at java.io.DataInputStream.readUTF(DataInputStream.java:594) ~[?:?] at java.io.DataInputStream.readUTF(DataInputStream.java:550) ~[?:?] at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:470) ~[guava-32.1.2-jre.jar:?]
> 
> ### Steps to reproduce
> 1. Use the item to long press the box
> 2. Enter the price
> 3. No response
> 
> ### Expected Behaviour
> Normally create a quickshop
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/24970475/332367735-bc62f56d-9717-4802-8124-b7fadedda6e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTc2MDYsIm5iZiI6MTcyMTYxNzMwNiwicGF0aCI6Ii8yNDk3MDQ3NS8zMzIzNjc3MzUtYmM2MmY1NmQtOTcxNy00ODAyLTgxMjQtYjdmYWRlZGRhNmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDAzMDE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZWQ5NmFkZmU1NGMxMjFhOGZhOGZmZmU2M2RiZTU4NDRiZmJkNzRlMjU2ZWRhMDFhZjcxM2E5ZGQxMDRlMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.edq8D_RrWOP5Ax5LbTOSX7nBtgF9VWOvTNrNjZWf1zg)
> 
> ### `/quickshop paste` URL
> https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FCucL2Rj0YM
> 
> ### Additional Context
> _No response_

is this still an issue on the latest releases?

**Comment by okkaradon** [comment]
It still happened on my 1.21.1 server.

- Paper 1.21.1 Build 89
- QuickShop-Hikari-6.2.0.7.jar
- Velocity 3.3.0-SNAPSHOT-436
- Compat-Velocity-6.2.0.7.jar

**Comment by creatorfromhell** [comment]
> It still happened on my 1.21.1 server.
> 
> * Paper 1.21.1 Build 89
> * QuickShop-Hikari-6.2.0.7.jar
> * Velocity 3.3.0-SNAPSHOT-436
> * Compat-Velocity-6.2.0.7.jar


[Compat-Velocity-6.2.0.7.zip](https://github.com/user-attachments/files/17172044/Compat-Velocity-6.2.0.7.zip)


Should be fine with this patch, just unzip and replace your velocity compact with the updated one.

**Comment by okkaradon** [comment]
The creation of the chestshop succeeded and the paper side error disappeared, but Velocity disconnects the player from the server with the following error
`
[09:47:37 FATAL]: A plugin tried to cancel a signed chat message. This is no longer possible in 1.19.1 and newer. Disconnecting player okkaradon`
![image](https://github.com/user-attachments/assets/0d2b2ae4-5871-4c71-bd28-9df34824100f)

**Comment by creatorfromhell** [comment]
> A plugin tried to cancel a signed chat message. This is no longer possible in 1.19.1 and newer.

This is a known limitation of Velocity. You'll have to use https://hangar.papermc.io/4drian3d/SignedVelocity per PaperMC team themselves. https://docs.papermc.io/velocity/faq#plugins-unable-to-modify-messages-or-commands
