### ISSUE TITLE
[BUG] /qs list PLAYER <page> doesn't work

### ISSUE THREAD

**Issue by codeHusky** [Ghost-chu/QuickShop-Hikari#1658]
### Description

When running, for example here, `/qs list gspt 2`, the server throws an error and fails to list the second page of results.

### Steps to reproduce

1. Create enough shops to have multiple pages
2. Run `/qs list <player> 2`
3. see error

### Expected Behaviour

The second page is shown

### Screenshots

![image](https://github.com/user-attachments/assets/ce7983c5-4382-4cac-be7b-f9601f8cd1ba)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2F9CAc3aIkcw

### Additional Context

```[22:45:43 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'qs list gspt 2' in com.ghostchu.quickshop.command.QuickShopCommand(quickshop)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[huskypaper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"a5dc4df"]
        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"a5dc4df"]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[huskypaper-1.20.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2208) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2168) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"a5dc4df"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"a5dc4df"]
        at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:193) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"a5dc4df"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"a5dc4df"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"a5dc4df"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"a5dc4df"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"a5dc4df"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[huskypaper-1.20.2.jar:git-HuskyPaper-"a5dc4df"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at com.ghostchu.quickshop.addon.list.command.SubCommand_List.onCommand(SubCommand_List.java:47) ~[QS-Addon-List-6.2.0.5.jar:?]
        at com.ghostchu.quickshop.addon.list.command.SubCommand_List.onCommand(SubCommand_List.java:25) ~[QS-Addon-List-6.2.0.5.jar:?]
        at com.ghostchu.quickshop.api.command.CommandHandler.onCommand_Internal(CommandHandler.java:76) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at com.ghostchu.quickshop.command.SimpleCommandManager.onCommand(SimpleCommandManager.java:446) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at com.ghostchu.quickshop.command.QuickShopCommand.execute(QuickShopCommand.java:22) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[huskypaper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 22 more
```

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [ ] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by creatorfromhell** [comment]
Fixed in the serialization PR that is in progress.
