### ISSUE TITLE
[BUG]  /qs history items can be taken

### ISSUE THREAD

**Issue by vermium** [Ghost-chu/QuickShop-Hikari#1659]
### Description

If user uses /qs history or via the controlpanel, they can take heads out of the gui. This is not expected

### Steps to reproduce

1. Install v6.2.0.5 of plugin
2. Create shop
3. Someone buys from shop
4. Check history of shop
5. Take something out of the GUI to your inventory

### Expected Behaviour

User should be prohibited from taking these items.

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FND78ywk9zx

### Additional Context

[16:31:50 ERROR]: Could not pass event InventoryDragEvent to QuickShop-Hikari v6.2.0.5
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at QuickShop-Hikari-6.2.0.5.jar/com.github.stefvanschie.inventoryframework.gui.GuiListener.onInventoryDrag(GuiListener.java:294) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor553.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-62-5a503d7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-62-5a503d7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-62-5a503d7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:480) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:382) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3059) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1542) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1519) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1512) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1471) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1323) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-62-5a503d7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:32:04 ERROR]: Could not pass event EntityPickupItemEvent to QuickShop-Hikari v6.2.0.5
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at QuickShop-Hikari-6.2.0.5.jar/com.github.stefvanschie.inventoryframework.gui.GuiListener.onEntityPickupItem(GuiListener.java:228) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor549.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-62-5a503d7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-62-5a503d7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-62-5a503d7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.item.ItemEntity.playerTouch(ItemEntity.java:515) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.world.entity.player.Player.touch(Player.java:639) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:604) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3173) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.world.entity.player.Player.tick(Player.java:288) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:836) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:346) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.network.Connection.tick(Connection.java:638) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:242) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1815) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1602) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1309) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-62-5a503d7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:32:22 ERROR]: Could not pass event EntityPickupItemEvent to QuickShop-Hikari v6.2.0.5
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at QuickShop-Hikari-6.2.0.5.jar/com.github.stefvanschie.inventoryframework.gui.GuiListener.onEntityPickupItem(GuiListener.java:228) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor549.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-62-5a503d7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-62-5a503d7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-62-5a503d7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.item.ItemEntity.playerTouch(ItemEntity.java:515) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.world.entity.player.Player.touch(Player.java:639) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:604) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3173) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.world.entity.player.Player.tick(Player.java:288) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:836) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:346) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.network.Connection.tick(Connection.java:638) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:242) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1815) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1602) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1309) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-62-5a503d7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:32:29 ERROR]: Could not pass event EntityPickupItemEvent to QuickShop-Hikari v6.2.0.5
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at QuickShop-Hikari-6.2.0.5.jar/com.github.stefvanschie.inventoryframework.gui.GuiListener.onEntityPickupItem(GuiListener.java:228) ~[QuickShop-Hikari-6.2.0.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor549.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-62-5a503d7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-62-5a503d7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-62-5a503d7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.item.ItemEntity.playerTouch(ItemEntity.java:515) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.world.entity.player.Player.touch(Player.java:639) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:604) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3173) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.world.entity.player.Player.tick(Player.java:288) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:836) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:346) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.network.Connection.tick(Connection.java:638) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:242) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1815) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1602) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1309) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-62-5a503d7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
#1632
