### ISSUE TITLE
[BUG] Failed to import the database from backup file.

### ISSUE THREAD

**Issue by DiamondBrain113** [Ghost-chu/QuickShop-Hikari#1820]
### Description

The plugin used to use H2 database, now when I migrate to MySQL, I ran the /quickshop recovery command and it shows this:
```
[16:00:58 WARN]: [QuickShop-Hikari] Failed to import the database from backup file.
java.sql.SQLException: Table not found: qs_data
        at QuickShop-Hikari-6.2.0.7.jar/org.relique.jdbc.csv.ZipFileTableReader.getReader(ZipFileTableReader.java:66) ~[QuickShop-Hikari-6.2.0.7.jar:?]
        at QuickShop-Hikari-6.2.0.7.jar/org.relique.jdbc.csv.CsvStatement.executeParsedQuery(CsvStatement.java:427) ~[QuickShop-Hikari-6.2.0.7.jar:?]
        at QuickShop-Hikari-6.2.0.7.jar/org.relique.jdbc.csv.CsvStatement.executeParsedQuery(CsvStatement.java:313) ~[QuickShop-Hikari-6.2.0.7.jar:?]
        at QuickShop-Hikari-6.2.0.7.jar/org.relique.jdbc.csv.CsvStatement.executeQuery(CsvStatement.java:306) ~[QuickShop-Hikari-6.2.0.7.jar:?]
        at QuickShop-Hikari-6.2.0.7.jar/com.ghostchu.quickshop.database.DatabaseIOUtil.importFromCSV(DatabaseIOUtil.java:104) ~[QuickShop-Hikari-6.2.0.7.jar:?]
        at QuickShop-Hikari-6.2.0.7.jar/com.ghostchu.quickshop.database.DatabaseIOUtil.importTables(DatabaseIOUtil.java:93) ~[QuickShop-Hikari-6.2.0.7.jar:?]
        at QuickShop-Hikari-6.2.0.7.jar/com.ghostchu.quickshop.command.subcommand.SubCommand_Recovery.lambda$onCommand$2(SubCommand_Recovery.java:48) ~[QuickShop-Hikari-6.2.0.7.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.4.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Steps to reproduce

1. Run /quickshop export on H2 db
2. Change to MySQL
3. Run /quickshop recovery

### Expected Behaviour

Shows success 

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FJmn6B0y0OB

### Additional Context

The shop works when on MySQL

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by creatorfromhell** [comment]
You need to stop, change the config, then start again to allow it to create the proper tables before doing the recovery.
