### ISSUE TITLE
[BUG] Dependency Conflicts with EasySQL

### ISSUE THREAD

**Issue by CarmJos** [Ghost-chu/QuickShop-Hikari#1827]
### Description

I'm the Main Developer of EasySQL, and I have made a series of plugins based on a Core Plugin witch compliled the EasySQL with original path.

And I got this error issues in my plugin's repository, see https://github.com/ArtformGames/UserSuffix/issues/7 .

```
[19:09:12 INFO]: [UserSuffix] Enabling UserSuffix v1.3.1
[19:09:12 INFO]: [UserSuffix]  _   _             ___       __  __ _
[19:09:12 INFO]: [UserSuffix] | | | |___ ___ _ _/ __|_  _ / _|/ _(_)_ __
[19:09:12 INFO]: [UserSuffix] | |_| (_-</ -_) '_\__ \ || |  _|  _| \ \ /
[19:09:12 INFO]: [UserSuffix]  \___//__/\___|_| |___/\_,_|_| |_| |_/_\_\
[19:09:12 INFO]: [UserSuffix]  UserSuffix v1.3.1
[19:09:12 INFO]: [UserSuffix] UserSuffix 1.3.1 开始启动...
[19:09:12 INFO]: [UserSuffix] Loading plugin configurations...
[19:09:12 INFO]: [UserSuffix] Register handlers...
[19:09:12 ERROR]: Error occurred while enabling UserSuffix v1.3.1 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving interface method 'boolean cc.carm.lib.easysql.api.SQLTable.create(cc.carm.lib.easysql.api.SQLManager)' the class loader 'UserSuffix-1.3.1.jar' @648f3142 of the current class, com/artformgames/plugin/usersuffix/user/SuffixLoader, and the class loader 'QuickShop-Hikari-6.2.0.7.jar' @3e985be8 for the method's defining class, cc/carm/lib/easysql/api/SQLTable, have different Class objects for the type cc/carm/lib/easysql/api/SQLManager used in the signature (com.artformgames.plugin.usersuffix.user.SuffixLoader is in unnamed module of loader 'UserSuffix-1.3.1.jar' @648f3142, parent loader java.net.URLClassLoader @108c4c35; cc.carm.lib.easysql.api.SQLTable is in unnamed module of loader 'QuickShop-Hikari-6.2.0.7.jar' @3e985be8, parent loader java.net.URLClassLoader @108c4c35)
        at UserSuffix-1.3.1.jar/com.artformgames.plugin.usersuffix.user.SuffixLoader.<init>(SuffixLoader.java:27) ~[UserSuffix-1.3.1.jar:?]
        at UserSuffix-1.3.1.jar/com.artformgames.plugin.usersuffix.Main.initialize(Main.java:38) ~[UserSuffix-1.3.1.jar:?]
        at ArtCore-1.1.1.jar/cc.carm.lib.easyplugin.EasyPlugin.onEnable(EasyPlugin.java:71) ~[ArtCore-1.1.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:669) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:618) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:772) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:534) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[19:09:12 INFO]: [UserSuffix] Disabling UserSuffix v1.3.1
[19:09:12 INFO]: [ArtCore] Unregistering all handlers from #UserSuffix ...
```

It is easy to determine that the conflict is caused by the dependency call. So I checked the QuickShop-Hikari project and found that when it used libby to load and call this dependency, it did not relocate the path.

To avoid other problems, please consider to relocate the EasySQL(and other dependencies if not reloacted) from `cc.carm.lib.EasySQL` to `com.ghostchu.quickshop.shade.easysql`.

### Steps to reproduce

Using any projects that compiled EasySQL.

### Expected Behaviour

To avoid other problems, please consider to relocate the EasySQL(and other dependencies if not reloacted) from `cc.carm.lib.EasySQL` to `com.ghostchu.quickshop.shade.easysql`.

### `/quickshop paste` URL

N/A

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [ ] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by CarmJos** [comment]
Is there any ideas?

**Comment by creatorfromhell** [comment]
> Is there any ideas?

It will be moved when imported.

**Comment by CarmJos** [comment]
I have checked the codes, and found that it may need to edit `libraries.maven`'s format or simply declare that all dependencies should be relocated to `com.ghostchu.quickshop.shade.` if used.

Then, relocate them all in `pom.xml`.

In libby, using `relocate(String pattern, String relocatedPattern)` to apply relocations.

**Comment by creatorfromhell** [comment]
> I have checked the codes, and found that it may need to edit `libraries.maven`'s format or simply declare that all dependencies should be relocated to `com.ghostchu.quickshop.shade.` if used.
> 
> Then, relocate them all in `pom.xml`.
> 
> In libby, using `relocate(String pattern, String relocatedPattern)` to apply relocations.
> 
> 
> 

Yes, that's the plan, this just isn't a high priority issue for me currently.

**Comment by CarmJos** [comment]
Have you decided which method to use?

 I may be able to pr for it.

**Comment by creatorfromhell** [comment]
> Have you decided which method to use?
> 
> I may be able to pr for it.

Not really, either method would most likely work

**Comment by CarmJos** [comment]
Well, the question is relocating in libby need to bind to specific jar, which means current `libraries.maven` is hard to configured relocations if not change the format.

So do you mind if I changed `libraries.maven` to `dependencies.yaml` for complex dependencies' settings support?

**Comment by creatorfromhell** [comment]
> Well, the question is relocating in libby need to bind to specific jar, which means current `libraries.maven` is hard to configured relocations if not change the format.
> 
> So do you mind if I changed `libraries.maven` to `dependencies.yaml` for complex dependencies' settings support?

I don't mind at all.

**Comment by CarmJos** [comment]
example:

from
```text
cc.carm.lib:easysql-hikaricp:0.4.7@cc.carm.lib.easysql.hikari.HikariDataSource
```

to

```yaml
dependencies:
  - dependency: "cc.carm.lib:easysql-hikaricp:0.4.7"
    vailidate: "cc.carm.lib.easysql.hikari.HikariDataSource"
    relocations:
      - pattern: ""
        shaded: ""
```

or

```yaml
dependencies:
  - group: "cc.carm.lib"
    artifact: "easysql-hikaricp"
    version: "0.4.7"
    classifier: "" # if used
    test: "cc.carm.lib.easysql.hikari.HikariDataSource"
    relocations:
      - pattern: ""
        shaded: ""

```

**Comment by creatorfromhell** [comment]
> example:
> 
> from
> 
> ```
> cc.carm.lib:easysql-hikaricp:0.4.7@cc.carm.lib.easysql.hikari.HikariDataSource
> ```
> 
> to
> 
> ```yaml
> dependencies:
>   - dependency: "cc.carm.lib:easysql-hikaricp:0.4.7"
>     vailidate: "cc.carm.lib.easysql.hikari.HikariDataSource"
>     relocations:
>       - pattern: ""
>         shaded: ""
> ```
> 
> or
> 
> ```yaml
> dependencies:
>   - group: "cc.carm.lib"
>     artifact: "easysql-hikaricp"
>     version: "0.4.7"
>     classifier: "" # if used
>     test: "cc.carm.lib.easysql.hikari.HikariDataSource"
>     relocations:
>       - pattern: ""
>         shaded: ""
> ```

seems good

**Comment by creatorfromhell** [comment]
Probably going to pair this with #2060

**Comment by creatorfromhell** [comment]
Should be completed in #2103
