### ISSUE TITLE
Console Error [BUG] 

### ISSUE THREAD

**Issue by roracle** [Ghost-chu/QuickShop-Hikari#399]
### Description

Console error

```
[13:38:06] [Craft Scheduler Thread - 40 - QuickShop-Hikari/WARN]: [QuickShop-Hikari] Plugin QuickShop-Hikari v3.1.0.2 generated an exception while executing task 43
kong.unirest.UnirestException: org.apache.http.conn.ConnectTimeoutException: Connect to repo.codemc.io:443 [repo.codemc.io/45.141.57.117] failed: Connect timed out
	at kong.unirest.DefaultInterceptor.onFail(DefaultInterceptor.java:43) ~[?:?]
	at kong.unirest.CompoundInterceptor.lambda$onFail$2(CompoundInterceptor.java:54) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Collections$2.tryAdvance(Collections.java:4853) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
	at kong.unirest.CompoundInterceptor.onFail(CompoundInterceptor.java:56) ~[?:?]
	at kong.unirest.apache.ApacheClient.request(ApacheClient.java:138) ~[?:?]
	at kong.unirest.Client.request(Client.java:57) ~[?:?]
	at kong.unirest.BaseRequest.request(BaseRequest.java:359) ~[?:?]
	at kong.unirest.BaseRequest.asString(BaseRequest.java:212) ~[?:?]
	at com.ghostchu.quickshop.util.updater.NexusManager.fetchMetadata(NexusManager.java:59) ~[QuickShop-Hikari-3.1.0.2.jar:?]
	at com.ghostchu.quickshop.util.updater.NexusManager.updateCacheIfRequired(NexusManager.java:52) ~[QuickShop-Hikari-3.1.0.2.jar:?]
	at com.ghostchu.quickshop.util.updater.NexusManager.isLatest(NexusManager.java:40) ~[QuickShop-Hikari-3.1.0.2.jar:?]
	at com.ghostchu.quickshop.watcher.UpdateWatcher.lambda$init$0(UpdateWatcher.java:27) ~[QuickShop-Hikari-3.1.0.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.1.jar:git-Paper-86]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.1.jar:git-Paper-86]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to repo.codemc.io:443 [repo.codemc.io/45.141.57.117] failed: Connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.13.jar:4.5.13]
	at kong.unirest.apache.ApacheClient.request(ApacheClient.java:129) ~[?:?]
	... 13 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:543) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:594) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.13.jar:4.5.13]
	at kong.unirest.apache.ApacheClient.request(ApacheClient.java:129) ~[?:?]
	... 13 more
```

### Steps to reproduce

NA, build #239 

### Expected Behaviour

No console errors

### Screenshots

NA

### `/qs paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FV7ysFQm0dJ

**Comment by Ghost-chu** [comment]
It seems just random Internet connection error, you can safely ignore it.
